"""
This file was automatically generated by SwarmDF.

It reproduces the workflow configured in the GUI and can be used
to rerun the analysis outside the application.
"""

import datetime
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from pathlib import Path

from swarmdf import *

######################
# Input settings
######################

config = {'satellite ID': 'Swarm A', 'start time': datetime.datetime(2014, 12, 15, 1, 15), 'end time': datetime.datetime(2014, 12, 15, 1, 17), 'DT': 30.0, 'datasets2download': ['swarm_mag', 'superdarn', 'supermag', 'iridium_ampere', 'dmsp_ssies17', 'dmsp_ssies18'], 'conductance method': 'Zang & Paxton model', 'conductance parameters': {'kp': 4.0, 'f107': 100.0, 'background': 2.0}, 'grid parameters': {'L': 1500.0, 'W': 2000.0, 'Lres': 200.0, 'Wres': 200.0, 'wshift': 0.0}, 'regularization parameters': {'l1': 1.0, 'l2': 1.0}, 'gif speed': 550, 'lompeOSSE analysis': 0, 'time offset': 0, 'Gamera snapshot': 0}

######################
# Collect data
######################

# Path to data files
package_root = Path(__file__).resolve().parents[0]
data_path = str(package_root / "data" / "sample_datasets") + "/" 

# Fetch and load data
datahandler = DataManager(config["start time"], config["end time"], config["datasets2download"])
datasets = datahandler.datasets

######################
# Prepare input for Lompe  
######################

# Define individual analysis frames
lompe_input = LompeInput(config["satellite ID"], config["start time"], config["end time"], datasets)
grids, analysis_times = lompe_input.build_grids_around_swarm(config["DT"], config["grid parameters"])

# Prepare data objects for each analysis frame
data_objects_per_grid = lompe_input.prepare_lompe_input(grids, analysis_times) 

# Plot input (analysis grids along satellite tracks and data distribution)
lompe_input.plot_lompe_input(grids, analysis_times, data_objects_per_grid, config["gif speed"], show_global_data=True, show_plot=True)

######################
# Run Lompe analysis (along satellite trajectory)
######################

# Conductances
SHs, SPs = compute_conductances(config["conductance method"], analysis_times, grids, config["conductance parameters"])

# Regularization parameters
l1, l2 = config["regularization parameters"]['l1'], config["regularization parameters"]['l2']

# Build Lompe model for each analysis frame
lompe_models = run_lompe(analysis_times, grids, data_objects_per_grid, SHs, SPs, l1, l2)

# Plot output (reconstructed electrodynamics)
plot_lompe_output(lompe_models, config["satellite ID"], config["gif speed"], show_plot=True)    

######################
# LompeOSSE analysis (analysis)
######################

dolompeosse = config["lompeOSSE analysis"]
if dolompeosse:
    lompeOSSE_models, gamera_models = run_lompeOSSE(lompe_models, config["time offset"], config["Gamera snapshot"])
    plot_lompeOSSE_output(lompeOSSE_models, gamera_models, config["gif speed"], show_plot=True)

    

# TODO remove?
# # Example usage:

# # Access individual Lompe model

# models = [entry["model"] for entry in lompe_models]
# model0 = models[0] 
# grid = model0.grid_E

# # Plot FACs

# facs = model0.FAC(grid.lon, grid.lat).reshape(grid.lon.shape)
# fac_levels = np.linspace(-1.95, 1.95, 40) * 1e-6 * 2

# fig, ax = plt.subplots(figsize=(8, 8))
# csax1 = cs.CSplot(ax, grid, gridtype='cs')
# csax1.contour(grid.lon, grid.lat, facs, colors='k')
# ax.set_title("")

