"""
This file was automatically generated by SwarmDF.

It reproduces the workflow configured in the GUI and can be used
to rerun the analysis outside the application.
"""

import datetime
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Uncomment if weird kernel crash
# import matplotlib
# matplotlib.use("TkAgg")

from swarmdf import *

######################
# Input settings
######################

config = {'satellite ID': 'Swarm A', 'start time': datetime.datetime(2014, 12, 15, 1, 10), 'end time': datetime.datetime(2014, 12, 15, 1, 20), 'DT': 30.0, 'datasets2download': ['swarm_mag', 'superdarn', 'supermag', 'iridium_ampere', 'dmsp_ssies17', 'dmsp_ssies18'], 'conductance method': 'Zang & Paxton model', 'conductance parameters': {'kp': 4.0, 'f107': 100.0, 'background': 2.0}, 'grid parameters': {'L': 2000.0, 'W': 1500.0, 'Lres': 200.0, 'Wres': 200.0, 'wshift': 0.0}, 'regularization parameters': {'l1': 1.0, 'l2': 1.0}, 'gif speed': 550, 'magnetic coordinates': False, 'lompeOSSE analysis': 0, 'time offset': 0, 'Gamera snapshot': 0}

######################
# Retrieve and load data
######################

datahandler = DataManager(config["start time"], config["end time"], config["datasets2download"])
datasets = datahandler.datasets

######################
# Prepare input for Lompe  
######################

# Define individual analysis frames (grid)
lompe_input = LompeInput(config["satellite ID"], config["start time"], config["end time"], datasets, config["magnetic coordinates"])
grids, analysis_times = lompe_input.build_grids_around_swarm(config["DT"], config["grid parameters"])

# Prepare data objects for each analysis frame
data_objects_per_grid = lompe_input.prepare_lompe_input(grids, analysis_times) 

# Plot input (analysis grids along satellite tracks and data distribution)
input_figs = lompe_input.plot_lompe_input(grids, analysis_times, data_objects_per_grid, gif_speed = config["gif speed"], show_global_data=True)

for frame in input_figs:
    plt.figure(figsize=(8, 6))
    plt.imshow(np.array(frame))
    plt.axis("off")
    plt.show()

######################
# Run Lompe analysis (along satellite trajectory)
######################

# Conductances
SHs, SPs = compute_conductances(config["conductance method"], analysis_times, grids, config["conductance parameters"])

# Regularization parameters
l1, l2 = config["regularization parameters"]['l1'], config["regularization parameters"]['l2']

# Build Lompe model for each analysis frame
lompe_models = run_lompe(analysis_times, grids, data_objects_per_grid, SHs, SPs, l1, l2)

# Plot output (reconstructed electrodynamics)
output_figs = plot_lompe_output(lompe_models, config["satellite ID"], gif_speed=config["gif speed"])    

for frame in output_figs:
    plt.figure(figsize=(8, 6))
    plt.imshow(np.array(frame))
    plt.axis("off")
    plt.show()
    

