"""
SwarmDF — Script generation module

Automatically generates a standalone Python script from GUI configuration settings.
    
"""

from pathlib import Path

def generate_python_code(config, fn):
    """
    Generate a standalone Python script from user input in the GUI. 
    
    The generated script reproduces a full SwarmDF workflow, including 
    data loading, Lompe model setup and analysis, and optional LompeOSSE validation.

    Parameters
    ----------
    config : dict
        Configuration dictionary generated from GUI inputs.
    fn : str
        Output filename for the generated Python script.
    """

    config_code = f"""
config = SwarmDFConfig(sat_id={config.sat_id!r},
                       start_time={config.start_time!r},
                       end_time={config.end_time!r},
                       timestep={config.timestep!r},
                       datasets2download={config.datasets2download!r},
                       conductance_method={config.conductance_method!r},
                       conductance_params={config.conductance_params!r},
                       grid_params={config.grid_params!r},
                       run_lompe_flag={config.run_lompe_flag!r},
                       l1={config.l1!r},
                       l2={config.l2!r},
                       speed={config.gif_speed!r},
                       figw={config.figw!r},
                       figh={config.figh!r},
                       mag={config.mag!r},
                       show_data={config.show_data!r},
                       run_validation_flag={config.run_validation_flag!r},
                       timeoff={config.timeoff!r},
                       snapshot={config.snapshot!r},
                       generate_script_flag={config.generate_script_flag!r}, 
                       demo_flag={config.demo_flag!r})
"""

    code = f'''"""
This file was automatically generated by SwarmDF.

It reproduces the workflow configured in the GUI and can be used
to rerun the analysis outside the application.
"""

import datetime
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from swarmdf.gui.config import SwarmDFConfig
from swarmdf.pipeline import run_swarmdf_pipeline

# Uncomment if weird kernel crash
# import matplotlib
# matplotlib.use("TkAgg")

from swarmdf import *

######################
# Input settings
######################

{config_code}

######################
# Retrieve and load data
######################

datahandler = DataManager(config.start_time, config.end_time, config.datasets2download, config.demo_flag)
datasets = datahandler.datasets

######################
# Prepare input for Lompe  
######################

# Define individual analysis frames (grid)
lompe_input = LompeInput(config.sat_id, config.start_time, config.end_time, datasets, config.mag)
grids, analysis_times = lompe_input.build_grids_around_swarm(config.timestep, config.grid_params)

# Prepare data objects for each analysis frame
data_objects_per_grid = lompe_input.prepare_lompe_input(grids, analysis_times) 

# Plot input (analysis grids along satellite tracks and data distribution)
input_figs = lompe_input.plot_lompe_input(grids, analysis_times, data_objects_per_grid, config.figh, config.figw, config.gif_speed, config.show_data)

%matplotlib inline
for frame in input_figs:
    plt.figure(figsize=(8, 6))
    plt.imshow(np.array(frame))
    plt.axis("off")
    plt.show()

######################
# Run Lompe analysis (along satellite trajectory)
######################

if config.run_lompe_flag:

    # Conductances
    SHs, SPs = compute_conductances(config.conductance_method, config.conductance_params, analysis_times, grids)

    # Regularization parameters
    l1, l2 = config.l1, config.l2

    # Build Lompe model for each analysis frame
    lompe_models = run_lompe(analysis_times, grids, data_objects_per_grid, SHs, SPs, l1, l2)

    # Plot output (reconstructed electrodynamics)
    output_figs = plot_lompe_output(lompe_models, config.sat_id, config.figh, config.gif_speed)    

    for frame in output_figs:
        plt.figure(figsize=(8, 6))
        plt.imshow(np.array(frame))
        plt.axis("off")
        plt.show()

######################
# LompeOSSE analysis (validation)
######################

if config.run_validation_flag:
    lompeOSSE_models, gamera_output = run_lompeOSSE(lompe_models, config.timeoff, config.snapshot)
    lompeosse_figs, gamera_figs = plot_lompeOSSE_output(lompeOSSE_models, gamera_output, config.figh, config.gif_speed)

    for osse_frame, gamera_frame in zip(lompeosse_figs, gamera_figs):
        fig, ax = plt.subplots(1, 2, figsize=(10, 5))
        ax[0].imshow(np.array(osse_frame))
        ax[0].axis("off")
        ax[1].imshow(np.array(gamera_frame))
        ax[1].axis("off")
        plt.tight_layout()
        plt.show()
    

# # Access individual Lompe model
# models = [entry["model"] for entry in lompe_models]
# model0 = models[0] 



# ######################
# # Run pipeline (no details) #TODO probably does not belong here, put it in read me file or something
# ######################

# results = run_swarmdf_pipeline(config)

# for frame in results.input.input_PILframes:
#     plt.figure(figsize=(8, 6))
#     plt.imshow(np.array(frame))
#     plt.axis("off")
#     plt.show()

# if config.run_lompe_flag:
#     for frame in results.output.output_PILframes:
#         plt.figure(figsize=(8, 6))
#         plt.imshow(np.array(frame))
#         plt.axis("off")
#         plt.show()

# if config.run_validation_flag:
#     for framea, frameb in zip(results.validation.lompeOSSE_PILframes, results.validation.gamera_PILframes):
#         fig, ax = plt.subplots(1, 2, figsize=(10, 5))
#         ax[0].imshow(np.array(framea))
#         ax[0].axis("off")
#         ax[1].imshow(np.array(frameb))
#         ax[1].axis("off")
#         plt.tight_layout()
#         plt.show()

'''

    # Export generated python file
    package_root = Path(__file__).resolve().parents[1]
    data_path = str(package_root) + "/"
    if not fn.endswith(".py"):
        fn += ".py"
    filename = data_path + fn # TODO ok place to save this code? maybe the example folder is best?
    with open(filename, "w") as f:
        f.write(code)

    print(f"SwarmDF Python script with current configuration exported to {filename}")