from pathlib import Path

def build_config_dict(sat_id, start_time, end_time, timestep, datasets, conductance_method, conductance_params, grid_params, regul_params, gif_speed, lompeosse, Gtimeoff, Gsnapshot):
    return {
        "satellite ID": sat_id,
        "start time": start_time,
        "end time": end_time,
        "DT": timestep,
        "datasets2download": datasets,
        "conductance method": conductance_method,
        "conductance parameters": conductance_params,
        "grid parameters": grid_params,
        "regularization parameters": regul_params,
        "gif speed": gif_speed,
        "lompeOSSE analysis": lompeosse,
        "time offset": Gtimeoff,
        "Gamera snapshot": Gsnapshot
    }

def generate_python_code(config):

    code = f'''
    """
    This file was automatically generated by SwarmDF.
    It recreates the Lompe model configured in the GUI.
    """

    import datetime
    import matplotlib.pyplot as plt
    import pandas as pd
    import numpy as np
    from pathlib import Path

    from swarmdf import *

    config = {repr(config)}

    # Duration of satellite orbit covered by each (animation) frame
    timestep = config["DT"] # [s]
    start_time = config["start time"]
    end_time = config["end time"]

    grid_params = config["grid parameters"]

    gif_speed = config["gif speed"]

    ######################
    # Collect data
    ######################

    # Path to sample datasets
    package_root = Path(__file__).resolve().parents[0]
    data_path = str(package_root / "data" / "sample_datasets") + "/" 

    # Fetch and load data
    datahandler = DataManager(start_time, data_path, config["datasets2download"])
    datasets = datahandler.datasets

    ######################
    # Data distrubution and orbit trajectory
    ######################

    center_times, grids, data_frames = swarm_trajectory(config["satellite ID"], start_time, end_time, timestep, grid_params, datasets, gif_speed, show_data=True)

    ######################
    # Lompe analysis
    ######################

    SHs, SPs = compute_conductances(config["conductance method"], start_time, end_time, timestep, grids, config["conductance parameters"])

    # Build model
    l1, l2 = config["regularization parameters"]['l1'], config["regularization parameters"]['l2']
    lompe_models = run_lompe(center_times, timestep, grids, datasets, SHs, SPs, l1, l2)
    lompe_frames = lompe_output(lompe_models, gif_speed)    
    

    # Example usage:

    # models = [entry["model"] for entry in lompe_models]
    # model0 = models[0]
    # grid = model0.grid_E
    # facs = model0.FAC(grid.lon, grid.lat).reshape(grid.lon.shape)

    # fac_levels = np.linspace(-1.95, 1.95, 40) * 1e-6 * 2

    # fig, ax = plt.subplots(figsize=(8, 8))
    # csax1 = cs.CSplot(ax, grid, gridtype='cs')
    # csax1.contour(grid.lon, grid.lat, facs, colors='k')
    # ax.set_title("")

    ######################
    # Validation / LompeOSSE analysis
    ######################
    
    dolompeosse = config["lompeOSSE analysis"]
    if dolompeosse:
        lompeOSSE_models, gamera_models = run_lompeOSSE(lompe_models, config["time offset"], config["Gamera snapshot"])
        lompeOSSE_frames, gamera_frames_pil = lompeOSSE_output(lompeOSSE_models, gamera_models, gif_speed)


    '''
    package_root = Path(__file__).resolve().parents[1]
    data_path = str(package_root) + "/"
    filename = data_path + "SwarmDF_python_code.py"
    with open(filename, "w") as f:
        f.write(code)

    print(f"Python code exported to {filename}")