
"""
SwarmDF — Script generation module

Automatically generates a standalone Python script from GUI configuration settings.
    
"""

from pathlib import Path

def build_config_dict(sat_id, start_time, end_time, timestep, datasets, conductance_method, conductance_params, grid_params, regul_params, gif_speed, lompeosse, Gtimeoff, Gsnapshot):
    """
    Configuration dictionary from GUI inputs.
    """
    
    return {
        "satellite ID": sat_id, 
        "start time": start_time,
        "end time": end_time,
        "DT": timestep,
        "datasets2download": datasets,
        "conductance method": conductance_method,
        "conductance parameters": conductance_params,
        "grid parameters": grid_params,
        "regularization parameters": regul_params,
        "gif speed": gif_speed,
        "lompeOSSE analysis": lompeosse,
        "time offset": Gtimeoff,
        "Gamera snapshot": Gsnapshot
    }

def generate_python_code(config, fn):
    """
    Generate a standalone Python script from user input in the GUI. 
    
    The generated script reproduces a full SwarmDF workflow, including 
    data loading, Lompe model setup and analysis, and optional LompeOSSE validation.

    Parameters
    ----------
    config : dict
        Configuration dictionary generated from GUI inputs.
    fn : str
        Output filename for the generated Python script.
    """

    code = f'''"""
This file was automatically generated by SwarmDF.

It reproduces the workflow configured in the GUI and can be used
to rerun the analysis outside the application.
"""

import datetime
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from pathlib import Path

from swarmdf import *

######################
# Input settings
######################

config = {repr(config)}

######################
# Collect data
######################

# Path to data files
package_root = Path(__file__).resolve().parents[0]
data_path = str(package_root / "data" / "sample_datasets") + "/" 

# Fetch and load data
datahandler = DataManager(config["start time"], config["end time"], data_path, config["datasets2download"])
datasets = datahandler.datasets

######################
# Prepare input for Lompe  
######################

# Define individual analysis frames
lompe_input = LompeInput(config["satellite ID"], config["start time"], config["end time"], datasets)
grids, analysis_times = lompe_input.build_grids_around_swarm(config["DT"], config["grid parameters"])

# Prepare data objects for each analysis frame
data_objects_per_grid = lompe_input.prepare_lompe_input(grids, analysis_times) 

# Plot input (analysis grids along satellite tracks and data distribution)
lompe_input.plot_lompe_input(grids, analysis_times, data_objects_per_grid, config["gif speed"], show_global_data=True, show_plot=False)

######################
# Run Lompe analysis (along satellite trajectory)
######################

# Conductances
SHs, SPs = compute_conductances(config["conductance method"], analysis_times, grids, config["conductance parameters"])

# Regularization parameters
l1, l2 = config["regularization parameters"]['l1'], config["regularization parameters"]['l2']

# Build Lompe model for each analysis frame
lompe_models = run_lompe(analysis_times, grids, data_objects_per_grid, SHs, SPs, l1, l2)

# Plot output (reconstructed electrodynamics)
plot_lompe_output(lompe_models, config["satellite ID"], config["gif speed"], show_plot=False)    

######################
# LompeOSSE analysis (analysis)
######################

dolompeosse = config["lompeOSSE analysis"]
if dolompeosse:
    lompeOSSE_models, gamera_models = run_lompeOSSE(lompe_models, config["time offset"], config["Gamera snapshot"])
    plot_lompeOSSE_output(lompeOSSE_models, gamera_models, config["gif speed"], show_plot=False)

    

# TODO remove?
# # Example usage:

# # Access individual Lompe model

# models = [entry["model"] for entry in lompe_models]
# model0 = models[0] 
# grid = model0.grid_E

# # Plot FACs

# facs = model0.FAC(grid.lon, grid.lat).reshape(grid.lon.shape)
# fac_levels = np.linspace(-1.95, 1.95, 40) * 1e-6 * 2

# fig, ax = plt.subplots(figsize=(8, 8))
# csax1 = cs.CSplot(ax, grid, gridtype='cs')
# csax1.contour(grid.lon, grid.lat, facs, colors='k')
# ax.set_title("")

'''

    # Export generated python file
    package_root = Path(__file__).resolve().parents[1]
    data_path = str(package_root) + "/"
    if not fn.endswith(".py"):
        fn += ".py"
    filename = data_path + fn # TODO ok place to save this code? maybe the example folder is best?
    with open(filename, "w") as f:
        f.write(code)

    print(f"Python code exported to {filename}")