"""
SwarmDF — Script generation module

Automatically generates a standalone Python script from GUI configuration settings.
    
"""

from pathlib import Path

def generate_python_code(config, plot_settings, fn):
    """
    Generate a standalone Python script from user input in the GUI. 
    
    The generated script reproduces a full SwarmDF workflow, including 
    data loading, Lompe model setup and analysis, and optional LompeOSSE validation.

    Parameters
    ----------
    config : dict
        Configuration dictionary generated from GUI inputs.
    fn : str
        Output filename for the generated Python script.
    """

    config_code = f"""
config = SwarmDFConfig(sat_id={config.sat_id!r},
                       start_time={config.start_time!r},
                       end_time={config.end_time!r},
                       timestep={config.timestep!r},
                       datasets2download={config.datasets2download!r},
                       conductance_method={config.conductance_method!r},
                       conductance_params={config.conductance_params!r},
                       grid_params={config.grid_params!r},
                       run_lompe_flag={config.run_lompe_flag!r},
                       regularization_l1={config.regularization_l1!r},
                       regularization_l2={config.regularization_l2!r},
                       run_validation_flag={config.run_validation_flag!r},
                       time_offset={config.time_offset!r},
                       snapshot={config.snapshot!r})
    
plot_settings = SwarmDFPlotSettings(figh={plot_settings.figh!r},
                                    mag_coords_flag={plot_settings.mag_coords_flag!r},
                                    show_all_data_flag={plot_settings.show_all_data_flag!r},
                                    gif_speed={plot_settings.gif_speed!r},
                                    generate_input_plots={plot_settings.generate_input_plots!r}, 
                                    generate_gifs={plot_settings.generate_gifs!r})
"""
                                                   
    code = f'''"""
This file was automatically generated by SwarmDF.

It reproduces the workflow configured in the GUI and can be used
to rerun the analysis outside the application.
"""

import datetime
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
import numpy as np
from PIL import Image 

from swarmdf.config import SwarmDFConfig, SwarmDFPlotSettings
from swarmdf.pipeline import *
from swarmdf import *

# Uncomment if weird kernel crash
# import matplotlib
# matplotlib.use("TkAgg")

matplotlib.rcParams['figure.dpi'] = 200

######################
# Input settings
######################

is_demo = False # set to True to use example configuration and sample datasets
{config_code}

######################
# Retrieve and load data
######################

datasets = get_data(config, is_demo)

######################
# Prepare input for Lompe  
######################

swarmdf_input = compute_swarmdf_input(datasets, config)

if plot_settings.generate_input_plots:
    input_figs = render_swarmdf_input(swarmdf_input, plot_settings)

    %matplotlib inline
    for input_fig in input_figs:
        plt.figure(figsize=(8, 6))
        plt.imshow(Image.open(input_fig))
        plt.axis("off")
        plt.show()

######################
# Run Lompe analysis (along satellite trajectory)
######################

if config.run_lompe_flag:

    swarmdf_output = compute_swarmdf_output(swarmdf_input, config)

    output_figs = render_swarmdf_output(swarmdf_output, plot_settings)   

    for output_fig in output_figs:
        plt.figure(figsize=(8, 6))
        plt.imshow(Image.open(output_fig))
        plt.axis("off")
        plt.show()

######################
# LompeOSSE analysis (validation)
######################
    
if config.run_validation_flag and config.run_lompe_flag is not None:

    swarmdf_validation = compute_swarmdf_validation(swarmdf_output, config)

    lompeosse_figs, gamera_figs = render_swarmdf_validation(swarmdf_validation, plot_settings)

    for lompeosse_fig, gamera_fig in zip(lompeosse_figs, gamera_figs):
        fig, ax = plt.subplots(1, 2, figsize=(10, 5))
        ax[0].imshow(Image.open(lompeosse_fig))
        ax[0].axis("off")
        ax[1].imshow(Image.open(gamera_fig))
        ax[1].axis("off")
        plt.tight_layout()
        plt.show()
    

# # Access individual Lompe model
# models = [entry["model"] for entry in lompe_models]
# model0 = models[0] 

'''

    # Export generated python file
    package_root = Path(__file__).resolve().parents[1]
    data_path = str(package_root) + "/"
    if not fn.endswith(".py"):
        fn += ".py"
    filename = data_path + fn # TODO ok place to save this code? maybe the example folder is best?
    with open(filename, "w") as f:
        f.write(code)

    print(f"SwarmDF Python script with current configuration exported to {filename}")